// TanStack adapter: Router/Start integration
//
// Handles:
//   - File-based route generation for TanStack Router
//   - Route tree generation from src/routes/
//   - Code splitting per route
//   - Type-safe route links
//   - TanStack Start SSR manifest

use anyhow::Result;
use std::path::{Path, PathBuf};

/// TanStack adapter configuration
pub struct TanStackAdapter {
    /// Project root
    pub root: PathBuf,
    /// Routes directory (default: src/routes)
    pub routes_dir: PathBuf,
    /// Detected routes
    pub routes: Vec<TanStackRoute>,
}

#[derive(Debug, Clone)]
pub struct TanStackRoute {
    /// Route path (e.g., "/", "/about", "/posts/$id")
    pub path: String,
    /// File path relative to project root
    pub file: String,
    /// Route name (derived from file path)
    pub name: String,
    /// Parent route path (for nesting)
    pub parent: Option<String>,
    /// Dynamic params (e.g., ["$id"])
    pub params: Vec<String>,
    /// Is this a layout route
    pub is_layout: bool,
}

impl TanStackAdapter {
    pub fn new(root: &Path) -> Self {
        let routes_dir = root.join("src").join("routes");
        Self {
            root: root.to_path_buf(),
            routes_dir,
            routes: Vec::new(),
        }
    }

    /// Discover all routes from src/routes/
    pub fn discover_routes(&mut self) -> Result<()> {
        if !self.routes_dir.exists() || !self.routes_dir.is_dir() {
            return Ok(());
        }
        let routes_dir = self.routes_dir.clone();
        self.scan_routes(&routes_dir, "")?;
        Ok(())
    }

    fn scan_routes(&mut self, dir: &Path, prefix: &str) -> Result<()> {
        let entries = std::fs::read_dir(dir)?;

        for entry in entries {
            let entry = entry?;
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().to_string();

            if path.is_dir() {
                // Nested route directory
                let route_segment = if name.starts_with('$') {
                    // Dynamic param: $id → :id
                    name.clone()
                } else {
                    name.clone()
                };
                let new_prefix = if prefix.is_empty() {
                    format!("/{}", route_segment)
                } else {
                    format!("{}/{}", prefix, route_segment)
                };
                self.scan_routes(&path, &new_prefix)?;
            } else if name.ends_with(".tsx") || name.ends_with(".ts") {
                let stem = name.split('.').next().unwrap_or(&name);
                let (route_path, is_layout, params) = match stem {
                    "__root" | "root" => ("/".to_string(), true, Vec::new()),
                    "index" => (
                        if prefix.is_empty() {
                            "/".to_string()
                        } else {
                            prefix.to_string()
                        },
                        false,
                        Vec::new(),
                    ),
                    _ => {
                        // Check for layout
                        let is_layout = stem == "layout" || stem.ends_with(".layout");
                        // Dynamic param
                        let mut params: Vec<String> = Vec::new();
                        let seg = if let Some(rest) = stem.strip_prefix('$') {
                            params.push(stem.to_string());
                            format!(":{}", rest)
                        } else {
                            stem.to_string()
                        };
                        let path = if prefix.is_empty() {
                            format!("/{}", seg)
                        } else {
                            format!("{}/{}", prefix, seg)
                        };
                        (path, is_layout, params)
                    }
                };

                let file_rel = path
                    .strip_prefix(&self.root)
                    .unwrap_or(&path)
                    .to_string_lossy()
                    .to_string();
                let route_name = stem.replace('$', "").replace('-', "_");

                self.routes.push(TanStackRoute {
                    path: route_path,
                    file: file_rel,
                    name: route_name,
                    parent: if prefix.is_empty() {
                        None
                    } else {
                        Some(prefix.to_string())
                    },
                    params,
                    is_layout,
                });
            }
        }

        Ok(())
    }

    /// Generate TanStack Router route tree code
    pub fn generate_route_tree(&self) -> String {
        let mut code = String::new();
        code.push_str("// Auto-generated by Pledge TanStack adapter\n");
        code.push_str("// TanStack Router route tree\n\n");

        // Import all route files
        for route in &self.routes {
            let import_path = format!("/{}", pledgepack_core::normalize_path_str(&route.file));
            code.push_str(&format!(
                "const {}Route = lazyRouteComponent(() => import('{}'));\n",
                route.name, import_path
            ));
        }

        code.push('\n');

        // Build route tree
        code.push_str("export const routeTree = {\n");
        for route in &self.routes {
            code.push_str(&format!(
                "  '{}': {{\n    component: {}Route,\n    path: '{}',\n    isLayout: {},\n  }},\n",
                route.path, route.name, route.path, route.is_layout
            ));
        }
        code.push_str("};\n\n");

        // Generate router setup
        code.push_str(
            r#"import { createRouter as createTanStackRouter } from '@tanstack/router';

export function createRouter(routes) {
  const routeTree = Object.entries(routes).map(([path, loader]) => ({
    path,
    component: () => loader().then(mod => mod.default),
  }));
  return createTanStackRouter({ routeTree });
}
"#,
        );

        code
    }

    /// Generate type-safe route links manifest
    pub fn generate_route_manifest(&self) -> String {
        let manifest: Vec<serde_json::Value> = self
            .routes
            .iter()
            .map(|r| {
                serde_json::json!({
                    "path": r.path,
                    "file": r.file,
                    "name": r.name,
                    "parent": r.parent,
                    "params": r.params,
                    "isLayout": r.is_layout,
                })
            })
            .collect();

        serde_json::to_string_pretty(&manifest).unwrap_or("[]".to_string())
    }
}

#[cfg(test)]
mod tests {
    // PRODUCTION-READINESS-100.md goal 69: zero tests existed for this
    // crate before this pass.
    use super::*;

    fn write_route(dir: &Path, rel: &str, content: &str) {
        let path = dir.join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, content).unwrap();
    }

    #[test]
    fn discovers_index_and_static_routes() {
        let tmp = tempfile::tempdir().unwrap();
        write_route(
            tmp.path(),
            "src/routes/index.tsx",
            "export default () => null;",
        );
        write_route(
            tmp.path(),
            "src/routes/about.tsx",
            "export default () => null;",
        );

        let mut adapter = TanStackAdapter::new(tmp.path());
        adapter.discover_routes().unwrap();

        let paths: Vec<&str> = adapter.routes.iter().map(|r| r.path.as_str()).collect();
        assert!(
            paths.contains(&"/"),
            "expected index route '/', got {paths:?}"
        );
        assert!(
            paths.contains(&"/about"),
            "expected '/about' route, got {paths:?}"
        );
    }

    #[test]
    fn discovers_dynamic_param_routes() {
        let tmp = tempfile::tempdir().unwrap();
        write_route(
            tmp.path(),
            "src/routes/posts/$id.tsx",
            "export default () => null;",
        );

        let mut adapter = TanStackAdapter::new(tmp.path());
        adapter.discover_routes().unwrap();

        let route = adapter
            .routes
            .iter()
            .find(|r| r.file.ends_with("$id.tsx"))
            .expect("dynamic route not discovered");
        assert_eq!(route.path, "/posts/:id");
        assert_eq!(route.params, vec!["$id".to_string()]);
    }

    #[test]
    fn discovers_root_and_nested_layout_routes() {
        let tmp = tempfile::tempdir().unwrap();
        write_route(
            tmp.path(),
            "src/routes/__root.tsx",
            "export default () => null;",
        );
        write_route(
            tmp.path(),
            "src/routes/dashboard/layout.tsx",
            "export default () => null;",
        );
        write_route(
            tmp.path(),
            "src/routes/dashboard/index.tsx",
            "export default () => null;",
        );

        let mut adapter = TanStackAdapter::new(tmp.path());
        adapter.discover_routes().unwrap();

        let root = adapter
            .routes
            .iter()
            .find(|r| r.file.ends_with("__root.tsx"))
            .unwrap();
        assert!(root.is_layout);

        let layout = adapter
            .routes
            .iter()
            .find(|r| {
                r.file.ends_with("dashboard/layout.tsx")
                    || r.file.ends_with("dashboard\\layout.tsx")
            })
            .unwrap();
        assert!(layout.is_layout);

        let nested_index = adapter
            .routes
            .iter()
            .find(|r| r.path == "/dashboard")
            .expect("nested index route should resolve to the parent prefix");
        assert!(!nested_index.is_layout);
    }

    #[test]
    fn missing_routes_directory_yields_no_routes_not_an_error() {
        let tmp = tempfile::tempdir().unwrap();
        let mut adapter = TanStackAdapter::new(tmp.path());
        let result = adapter.discover_routes();
        assert!(result.is_ok());
        assert!(adapter.routes.is_empty());
    }

    #[test]
    fn route_tree_codegen_includes_every_discovered_route() {
        let tmp = tempfile::tempdir().unwrap();
        write_route(
            tmp.path(),
            "src/routes/index.tsx",
            "export default () => null;",
        );
        write_route(
            tmp.path(),
            "src/routes/about.tsx",
            "export default () => null;",
        );

        let mut adapter = TanStackAdapter::new(tmp.path());
        adapter.discover_routes().unwrap();
        let tree = adapter.generate_route_tree();

        assert!(tree.contains("lazyRouteComponent"));
        for route in &adapter.routes {
            assert!(
                tree.contains(&format!("'{}'", route.path)),
                "generated route tree missing entry for '{}':\n{}",
                route.path,
                tree
            );
        }
    }

    #[test]
    fn route_manifest_is_valid_json_matching_discovered_routes() {
        let tmp = tempfile::tempdir().unwrap();
        write_route(
            tmp.path(),
            "src/routes/posts/$id.tsx",
            "export default () => null;",
        );

        let mut adapter = TanStackAdapter::new(tmp.path());
        adapter.discover_routes().unwrap();
        let manifest = adapter.generate_route_manifest();

        let parsed: serde_json::Value =
            serde_json::from_str(&manifest).expect("manifest must be valid JSON");
        let arr = parsed.as_array().expect("manifest must be a JSON array");
        assert_eq!(arr.len(), adapter.routes.len());
        assert_eq!(arr[0]["path"], "/posts/:id");
    }
}
