// Generated by scripts/generate-config-types.mjs from `pledgepack schema`.
// Do not edit by hand — run `pnpm run gen:types` after changing the config
// schema in crates/core/src/config.rs.

/** Accessibility linting configuration (#108) */
export interface A11yConfig {
  /**
   * Check for missing alt attributes on images
   * @default true
   */
  "checkAlt"?: boolean;
  /**
   * Check for ARIA labels on interactive elements
   * @default true
   */
  "checkAria"?: boolean;
  /**
   * Check for sufficient color contrast
   * @default false
   */
  "checkContrast"?: boolean;
  /**
   * Enable a11y linting during build (default: false)
   * @default false
   */
  "enabled"?: boolean;
  /**
   * Fail build on a11y errors (default: true)
   * @default true
   */
  "failOnError"?: boolean;
}

/** Bundle size budget configuration (#102) */
export interface BudgetConfig {
  /**
   * Enable budget checking (default: false)
   * @default false
   */
  "enabled"?: boolean;
  /** Per-entry-point budgets (entry name → max bytes) */
  "entryBudgets"?: Record<string, number>;
  /**
   * Maximum total bundle size in bytes (0 = no limit)
   * @default 0
   */
  "maxBundleSize"?: number;
  /**
   * Maximum number of chunks (0 = no limit)
   * @default 0
   */
  "maxChunkCount"?: number;
  /**
   * Maximum per-chunk size in bytes (0 = no limit)
   * @default 0
   */
  "maxChunkSize"?: number;
}

/** Build configuration for production builds */
export interface BuildConfig {
  /**
   * Asset inlining threshold in bytes (default: 4096)
Assets smaller than this are inlined as base64 data URIs
   * @default 4096
   */
  "assetsInlineLimit"?: number;
  /**
   * Emit decorator metadata for legacy decorators (default: false)
Mirrors tsconfig `compilerOptions.emitDecoratorMetadata`.
Only takes effect when legacy decorators are enabled.
   * @default false
   */
  "emitDecoratorMetadata"?: boolean;
  /**
   * Inline process.env.* variables at build time (default: true in production)
Replaces process.env.NODE_ENV with "production" / "development" and
tree-shakes unreachable branches (if (DEV) { ... } eliminated)
   * @default true
   */
  "envInline"?: boolean;
  /**
   * Enable TypeScript legacy ("experimental") decorators (default: false)
Mirrors tsconfig `compilerOptions.experimentalDecorators`; also
auto-detected from tsconfig.json when not enabled here.
   * @default false
   */
  "experimentalDecorators"?: boolean;
  /**
   * Enable font subsetting for production builds (default: false)
   * @default false
   */
  "fontSubsetting"?: boolean;
  /**
   * Incremental output: skip writing unchanged chunks in watch mode (default: true)
Compares content hashes and only writes files that changed
   * @default true
   */
  "incrementalOutput"?: boolean;
  /**
   * Inline dynamic imports into parent chunk instead of creating async chunks
   * @default false
   */
  "inlineDynamicImports"?: boolean;
  /**
   * Minify JSON modules in production (default: true)
   * @default true
   */
  "jsonMinify"?: boolean;
  /**
   * Manual chunk splitting configuration
Maps chunk name to list of module paths/globs to include
   */
  "manualChunks"?: Record<string, string[]>;
  /**
   * Generate modulepreload link tags for async chunks (default: true)
   * @default true
   */
  "modulePreload"?: boolean;
  /**
   * Polyfill modulepreload for older browsers (default: false)
   * @default false
   */
  "modulePreloadPolyfill"?: boolean;
  /**
   * Build concurrency: max parallel module transforms (default: auto-detect CPU cores)
Set to a specific number to limit concurrency and prevent OOM on large projects (#120)
   */
  "parallel"?: number | null;
  /**
   * Generate prefetch link tags for assets (default: false)
   * @default false
   */
  "prefetch"?: boolean;
  /**
   * Generate preload link tags for critical assets (default: false)
   * @default false
   */
  "preload"?: boolean;
  /**
   * Module preloading strategy for entry chunks (default: "lazy")
"eager" — preload all entry + async chunks via <link rel="modulepreload">
"lazy" — only preload entry chunks, async chunks loaded on demand
"manual" — don't auto-generate preload tags, user controls via HTML
   * @default "lazy"
   */
  "preloadStrategy"?: string;
  /**
   * Source map mode: "external" (default), "hidden", "inline", "nosources"
   * @default "external"
   */
  "sourceMapMode"?: string;
  /**
   * Enable SVG sprite generation (default: false)
   * @default false
   */
  "svgSprite"?: boolean;
  /**
   * JavaScript compilation target for syntax lowering (default: none — modern ES output)
Accepts esbuild-style targets ("es2020", "chrome90", "node18", "esnext")
or a browserslist query ("last 2 versions", "> 0.5%, not dead").
Falls back to the project's .browserslistrc / package.json browserslist
for browser builds when unset.
   */
  "target"?: string | null;
  /**
   * Run TypeScript type checking during build (default: false)
Integrates `tsc --noEmit` into the build pipeline
Fails build on type errors with formatted output
   * @default false
   */
  "typeCheck"?: boolean;
  /**
   * Verify build output integrity after emit (default: false)
Checks all chunks exist, no broken import references, all assets resolved
   * @default false
   */
  "verifyOutput"?: boolean;
  /**
   * WASM SIMD optimization (default: "auto")
"auto" — detect SIMD support from build target, generate optimized WASM
"always" — always generate SIMD-optimized WASM instantiation
"never" — always use non-SIMD fallback
   * @default "auto"
   */
  "wasmSimd"?: string;
}

export type BuildMode = "development" | "production";

export interface CacheConfig {
  /**
   * Cache directory (default: "node_modules/.pledge-cache")
   * @default "node_modules/.pledge-cache"
   */
  "dir"?: string;
  /**
   * Enable filesystem cache (default: true)
   * @default true
   */
  "enabled"?: boolean;
  /** Remote cache configuration (optional, for CI/team cache sharing) */
  "remote"?: RemoteCacheSettings;
}

/**
 * CSS configuration for RTL auto-generation (#107), dark mode (#67),
custom property optimization (#68), scoped CSS (#69)
 */
export interface CssConfig {
  /**
   * Dark mode generation strategy: "auto", "extract", "off" (default: "off")
#67 — auto-generate dark mode variants from prefers-color-scheme
   * @default "off"
   */
  "darkMode"?: string;
  /**
   * Minify CSS custom property names in production (default: false)
#68 — shortens --my-color to --a etc.
   * @default false
   */
  "minifyCustomPropertyNames"?: boolean;
  /**
   * Optimize CSS custom properties: inline static vars, remove unused (default: true in production)
#68 — detect and inline static custom properties, remove unused :root variables
   * @default false
   */
  "optimizeCustomProperties"?: boolean;
  /**
   * RTL CSS generation mode: "auto", "manual", "off" (default: "off")
   * @default "off"
   */
  "rtl"?: string;
  /**
   * Scoped CSS strategy: "attribute", "modules", "off" (default: "off")
#69 — data-v-xxxxx attribute-based scoping like Vue for React components
   * @default "off"
   */
  "scoped"?: string;
}

/** CSS preprocessor configuration for multi-preprocessor support */
export interface CssPreprocessorConfig {
  /**
   * Enable Less support (default: true if .less files detected)
   * @default false
   */
  "less"?: boolean;
  /** Additional CSS plugin paths */
  "plugins"?: string[];
  /**
   * Enable Sass/SCSS support (default: true, built-in via grass crate)
   * @default false
   */
  "sass"?: boolean;
  /**
   * Enable Stylus support (default: true if .styl files detected)
   * @default false
   */
  "stylus"?: boolean;
}

export interface DevServerConfig {
  /**
   * Access token required (as `?token=` or an `X-Pledge-Token` header) to
reach any dev-server route. If unset and `host` is bound to a
non-loopback address, one is auto-generated and printed at startup —
mirroring how e.g. Jupyter protects LAN-exposed sessions. Set to an
empty string to explicitly disable (loopback binds never require a
token regardless of this setting). See goal 18.
   */
  "accessToken"?: string | null;
  /**
   * CORS policy (default: same-origin). Previously the dev server sent
`Access-Control-Allow-Origin: *` unconditionally on every route,
including the raw-filesystem `/@fs/*` handler — any webpage open in
the same browser could read project files cross-origin. See
PRODUCTION-READINESS-100.md goal 16.
   * @default "same-origin"
   */
  "cors"?: DevServerCors;
  /**
   * Enable HMR (default: true)
   * @default true
   */
  "hmr"?: boolean;
  /**
   * Host (default: "localhost")
   * @default "localhost"
   */
  "host"?: string;
  /**
   * HTTPS support (default: false)
   * @default false
   */
  "https"?: boolean;
  /** Middleware functions to apply to the dev server (JS source code) */
  "middleware"?: string[];
  /**
   * Open browser on start (default: false)
   * @default false
   */
  "open"?: boolean;
  /**
   * Port (default: 3000)
   * @default 3000
   */
  "port"?: number;
  /**
   * Public directory for static assets (default: "public")
   * @default "public"
   */
  "publicDir"?: string;
  /**
   * Unix domain socket path to listen on instead of TCP host:port
(Unix platforms only, default: none)
   */
  "unixSocket"?: string | null;
}

/** CORS policy for the dev server. See [`DevServerConfig::cors`]. */
export type DevServerCors = string;

/** Build-time string encryption configuration (#109) */
export interface EncryptConfig {
  /**
   * Enable string encryption (default: false)
   * @default false
   */
  "enabled"?: boolean;
  /** Encryption key (32-byte hex string). If not set, generated at build time. */
  "key"?: string | null;
  /** Keys to encrypt (from process.env or define) */
  "keys"?: string[];
}

/** Conditional exports resolution configuration (#119) */
export interface ExportsConfig {
  /**
   * Additional conditions for package.json exports resolution
e.g., ["production", "browser"] to prefer production/browser entry points
   */
  "conditions"?: string[];
}

export type Framework = "pledge" | "react" | "vue" | "svelte" | "solid" | "next" | "tanstack" | "astro" | "auto";

/** GraphQL code generation configuration (#116) */
export interface GraphqlConfig {
  /**
   * Output directory for generated types (default: "src/generated")
   * @default "src/generated"
   */
  "output"?: string;
  /**
   * Generate React hooks for queries (default: false)
   * @default false
   */
  "reactHooks"?: boolean;
  /**
   * Path to schema file (e.g., "schema.graphql")
   * @default ""
   */
  "schema"?: string;
}

/** HTTPS configuration for dev server */
export interface HttpsConfig {
  /** Path to SSL certificate file */
  "cert": string;
  /** Path to SSL key file */
  "key": string;
}

/** i18n configuration for locale-aware bundling (#106) */
export interface I18nConfig {
  /**
   * Default locale (default: "en")
   * @default "en"
   */
  "defaultLocale"?: string;
  /**
   * Enable i18n-aware bundling (default: false)
   * @default false
   */
  "enabled"?: boolean;
  /**
   * Enable compile-time i18n key extraction from t('key') calls (#13)
   * @default false
   */
  "extract"?: boolean;
  /** Supported locales (e.g., ["en", "fr", "ja"]) */
  "locales"?: string[];
  /**
   * Message file pattern (default: "./messages.${locale}.json")
   * @default "./messages.${locale}.json"
   */
  "messagePattern"?: string;
}

/** Image optimization configuration */
export interface ImageConfig {
  /**
   * Enable AVIF conversion (default: false)
   * @default false
   */
  "avif"?: boolean;
  /**
   * Enable image optimization (default: false)
   * @default false
   */
  "enabled"?: boolean;
  /**
   * Max height in pixels (default: 1080)
   * @default 1080
   */
  "maxHeight"?: number;
  /**
   * Max width in pixels (default: 1920)
   * @default 1920
   */
  "maxWidth"?: number;
  /**
   * Default quality (1-100, default: 80)
   * @default 80
   */
  "quality"?: number;
  /**
   * Responsive srcset widths (#79) — e.g., [400, 800, 1200]
When set, auto-generates srcset with multiple resolutions
   */
  "responsiveWidths"?: number[];
  /**
   * Enable WebP conversion (default: true when enabled)
   * @default true
   */
  "webp"?: boolean;
}

/** Compiled-to-JS language configuration */
export interface LanguageConfig {
  /**
   * Enable CoffeeScript compilation (default: false)
   * @default false
   */
  "coffeescript"?: boolean;
  /**
   * Enable LiveScript compilation (default: false)
   * @default false
   */
  "livescript"?: boolean;
  /** Additional language transformers (plugin paths) */
  "transformers"?: string[];
}

/** Library mode configuration for building npm packages */
export interface LibraryConfig {
  /** Generate TypeScript declaration files */
  "declarations": boolean;
  /** Entry point for the library */
  "entry": string;
  /** External dependencies (not bundled) */
  "external": string[];
  /** Output formats (esm, cjs, umd) */
  "formats": OutputFormat[];
  /** Global variable name for UMD/IIFE */
  "name"?: string | null;
}

/** Nested optimization configuration (matches pledge.json format) */
export interface OptimizeConfig {
  /** Enable minification (default: true in production) */
  "minify"?: boolean | null;
  /** Enable code splitting (default: true in production) */
  "splitChunks"?: boolean | null;
  /** Enable tree shaking (default: true in production) */
  "treeShake"?: boolean | null;
}

export type OutputFormat = "esm" | "cjs" | "iife";

export interface PathAlias {
  "from": string;
  "to": string;
}

/**
 * Plugin trust policy (`plugin_security` / `pluginSecurity` in config).

Defaults to **signed plugins required**: every plugin in `plugins` must
carry a `<path>.sig.json` sidecar whose Ed25519 signature verifies
against one of `trusted_keys` and whose declared capabilities pass the
`CapabilityAuditor` policy. Set `require_signed = false` to opt out
entirely (unsigned plugins load, no capability audit — documented as
insecure, useful for local plugin development).
 */
export interface PluginSecurityConfig {
  /**
   * Extra capabilities to approve beyond the default policy
(e.g. "fs:write", "network", or custom strings).
   */
  "allowCapabilities"?: string[];
  /** Extra capabilities to deny beyond the default policy. */
  "denyCapabilities"?: string[];
  /**
   * Require a valid `.sig.json` sidecar from a trusted signer on every
plugin (default: true — unsigned plugins are refused).
   * @default true
   */
  "requireSigned"?: boolean;
  /**
   * Trusted signer identities → hex-encoded Ed25519 public keys. A
signature only verifies if its `(identity, public_key)` pair is
listed here — with no trusted keys configured and
`require_signed` on, every plugin is refused.
   */
  "trustedKeys"?: Record<string, string>;
}

export interface ProxyConfig {
  /** Additional headers to add to proxied requests */
  "headers"?: Record<string, string>;
  /** Path prefix to match (e.g., "/api") */
  "path": string;
  /**
   * Whether to rewrite the path (remove prefix)
   * @default false
   */
  "rewrite"?: boolean;
  /** Target URL to proxy to (e.g., "http://localhost:8080") */
  "target": string;
  /**
   * Enable WebSocket proxying (default: false)
   * @default false
   */
  "ws"?: boolean;
}

/** Settings for remote cache (S3/GCS/HTTP) */
export interface RemoteCacheSettings {
  /** Backend: "http", "s3", "gcs" */
  "backend": string;
  /** Bucket name (for S3/GCS) */
  "bucket"?: string | null;
  /** Enable remote cache (default: false) */
  "enabled": boolean;
  /** Endpoint URL */
  "endpoint": string;
  /** Namespace prefix for cache keys */
  "namespace"?: string | null;
  /** Region (for S3) */
  "region"?: string | null;
}

/** Nested resolve configuration (matches pledge.json format) */
export interface ResolveConfig {
  /** Path aliases as a map (e.g., { "@": "./src" }) */
  "alias"?: Record<string, string>;
  /** Conditions for package.json exports resolution */
  "conditions"?: string[];
  /** File extensions to resolve */
  "extensions"?: string[];
}

/** Security configuration for SRI (#81) and CSP (#82) */
export interface SecurityConfig {
  /**
   * Content Security Policy generation mode: "auto", "off" (default: "off")
#82 — auto-generate CSP headers from build output, writes _headers file
   * @default "off"
   */
  "csp"?: string;
  /**
   * Scan emitted client bundles for embedded secrets (private keys,
provider tokens, non-public `.env` values, high-entropy literals).
Default: on — recognized credentials fail the build, entropy-only
findings warn. Set `secretScan: false` to disable.
   * @default true
   */
  "secretScan"?: boolean;
  /**
   * Generate Subresource Integrity hashes for script/link tags (default: false)
#81 — SHA-256 integrity attributes
   * @default false
   */
  "sri"?: boolean;
}

/** A single service worker caching rule */
export interface SwCacheRule {
  /**
   * URL pattern to match (e.g., "/api/*")
   * @default ""
   */
  "pattern"?: string;
  /**
   * Caching strategy: "cache-first", "network-first", "stale-while-revalidate"
   * @default ""
   */
  "strategy"?: string;
}

/** Service worker caching configuration (#113) */
export interface SwCachingConfig {
  /**
   * Cache name prefix (default: "pledge-sw")
   * @default "pledge-sw"
   */
  "cacheName"?: string;
  /** Per-route caching rules */
  "caching"?: SwCacheRule[];
  /** Offline fallback page */
  "offlineFallback"?: string | null;
}

export type Target = "browser" | "node" | "worker" | "edge";

/** Build target configuration for multi-platform output */
export type TargetConfig = Target | Target[];

/** Template language configuration for server-side rendering */
export interface TemplateConfig {
  /**
   * Enable EJS template compilation (default: false)
   * @default false
   */
  "ejs"?: boolean;
  /** Template file extensions to process (default: auto-detect) */
  "extensions"?: string[];
  /**
   * Enable Handlebars template compilation (default: false)
   * @default false
   */
  "handlebars"?: boolean;
  /**
   * Enable Pug template compilation (default: false)
   * @default false
   */
  "pug"?: boolean;
}

/** Test configuration (Vitest-compatible) */
export interface TestConfig {
  /**
   * Whether to collect code coverage
   * @default false
   */
  "coverage"?: boolean;
  /**
   * Coverage report format: "text", "json", "html", "lcov"
   * @default "text"
   */
  "coverageReporter"?: string;
  /**
   * Test environment: "node" (default), "jsdom", "happy-dom"
   * @default "node"
   */
  "environment"?: string;
  /** Test file patterns to exclude */
  "exclude"?: string[];
  /**
   * Whether to run tests with globals (describe, it, expect) instead of imports
   * @default false
   */
  "globals"?: boolean;
  /** Test file patterns (default: ["**&#47;*.{test,spec}.{js,ts,jsx,tsx}"]) */
  "include"?: string[];
  /**
   * Test isolation mode: "file" (each file in own context), "pool" (shared pool), "none" (no isolation)
   * @default "file"
   */
  "isolation"?: string;
  /** Setup files to run before each test file */
  "setupFiles"?: string[];
  /**
   * Whether to enable snapshot testing
   * @default true
   */
  "snapshot"?: boolean;
  /**
   * Directory for snapshot files (default: "__snapshots__")
   * @default "__snapshots__"
   */
  "snapshotDir"?: string;
  /**
   * Whether to update snapshots automatically
   * @default false
   */
  "updateSnapshots"?: boolean;
}

/**
 * Custom transformer pipeline configuration (#97)
Allows inserting custom transform steps at any point in the pipeline
 */
export interface TransformPipelineConfig {
  /**
   * Ordered list of transform steps
Built-in steps: "oxc", "minify", "tree-shake"
Custom steps: plugin name or path to WASM/JS transformer
   */
  "pipeline"?: string[];
  /**
   * Whether to replace the default pipeline entirely (true) or insert into it (false)
   * @default false
   */
  "replaceDefault"?: boolean;
}

/** Watch mode configuration */
export interface WatchConfig {
  /**
   * Debounce interval in milliseconds
   * @default 100
   */
  "debounceMs"?: number;
  /**
   * Enable watch mode
   * @default false
   */
  "enabled"?: boolean;
}

/** Webhook configuration for build events (#105) */
export interface WebhookConfig {
  /**
   * Enable webhooks (default: false)
   * @default false
   */
  "enabled"?: boolean;
  /** Additional headers to send */
  "headers"?: Record<string, string>;
  /** URL to POST build results to on completion */
  "onBuild"?: string | null;
  /** URL to POST build errors to */
  "onError"?: string | null;
  /** Optional HMAC-SHA256 secret for signing webhook payloads */
  "secret"?: string | null;
}

/** Workspace configuration for monorepo support (#98, #99, #100) */
export interface WorkspaceConfig {
  /**
   * Enable cross-package HMR (#99) — propagate HMR across workspace packages
   * @default true
   */
  "crossPackageHmr"?: boolean;
  /**
   * Enable workspace-aware resolution (default: true when workspaces is set)
   * @default true
   */
  "enabled"?: boolean;
  /** Custom workspace root path (default: auto-detect from package.json) */
  "root"?: string | null;
  /**
   * Share build cache at workspace root (#100)
Cache directory will be placed at workspace root .pledge/ instead of per-package
   * @default true
   */
  "sharedCache"?: boolean;
}

/** Top-level configuration for the Pledge bundler. */
export interface PledgeConfig {
  /** Accessibility linting during build (#108) */
  "a11y"?: A11yConfig;
  /** Path aliases from tsconfig/jsconfig */
  "alias"?: PathAlias[];
  /**
   * App directory for file-based routing (e.g., "app" or "src/app")
When set, enables Next.js/Expo-style file-based routing:
  app/page.tsx          → /
  app/about/page.tsx    → /about
  app/blog/[slug]/page.tsx → /blog/:slug
  app/layout.tsx        → shared layout wrapper

Auto-detection order (when not explicitly set):
  1. src/app/  — if src/ exists, colocate routes with source
  2. app/      — flat structure at project root
   */
  "appDir"?: string | null;
  /**
   * Base path for deployment under a subpath (#84)
e.g., base: '/my-app/' — all asset URLs and import paths adjusted automatically
Default: "/" (root deployment)
   * @default "/"
   */
  "base"?: string;
  /** Bundle size budgets (#102)
Exit non-zero on budget violations in CI */
  "budgets"?: BudgetConfig;
  /** Build configuration for chunk splitting, source maps, asset inlining */
  "build"?: BuildConfig;
  /** Whether to enable the persistent filesystem cache */
  "cache"?: CacheConfig;
  /**
   * Whether to generate .br compressed output (default: false)
   * @default false
   */
  "compressBrotli"?: boolean;
  /**
   * Whether to generate .gz compressed output (default: false)
   * @default false
   */
  "compressGzip"?: boolean;
  /** Conditions for package.json exports resolution */
  "conditions"?: string[];
  /** CSS RTL auto-generation (#107) */
  "css"?: CssConfig;
  /** CSS preprocessor configuration */
  "cssPreprocessor"?: CssPreprocessorConfig;
  /** Compile-time constant replacement (define plugin) */
  "define"?: Record<string, string>;
  /** Dev server configuration */
  "devServer"?: DevServerConfig;
  /** Edge deployment target ("cloudflare", "vercel", "deno", or null) */
  "edgeTarget"?: string | null;
  /**
   * Build-time string encryption (#109)
Encrypt sensitive strings in source at build time
   */
  "encrypt"?: EncryptConfig;
  /** Entry points (e.g., ["src/index.tsx"]) */
  "entry"?: string[];
  /**
   * Whether to generate .d.ts for import.meta.env (default: true)
   * @default true
   */
  "envDts"?: boolean;
  /** Environment variable prefixes to inject (default: ["PLEDGE_"]) */
  "envPrefix"?: string[];
  /**
   * Conditional exports resolution (#119)
Additional conditions for package.json exports resolution
exports: { conditions: ['production', 'browser'] }
   */
  "exports"?: ExportsConfig | null;
  /**
   * File extensions to resolve (default: [".tsx", ".ts", ".jsx", ".js", ".json", ".css"])
   */
  "extensions"?: string[];
  /**
   * Module federation config (#115)
Share modules across independently deployed apps
federation: { name: 'host', remotes: { app1: 'http://cdn/app1.js' }, shared: ['react'] }
   */
  "federation"?: unknown;
  /**
   * Framework adapter ("react", "vue", "svelte", "solid", "auto")
   * @default "pledge"
   */
  "framework"?: Framework;
  /**
   * GraphQL code generation config (#116)
graphql: { schema: 'schema.graphql' }
   */
  "graphql"?: GraphqlConfig | null;
  /** HTML entry point (default: "index.html") */
  "htmlEntry"?: string | null;
  /** HTTPS configuration for dev server */
  "https"?: HttpsConfig | null;
  /**
   * i18n-aware bundling (#106)
Split bundles by locale, only load current locale's strings
   */
  "i18n"?: I18nConfig;
  /** Image optimization config */
  "image"?: ImageConfig;
  /** Compiled-to-JS language configuration (CoffeeScript, LiveScript) */
  "languages"?: LanguageConfig;
  /** Library mode configuration (for building npm packages) */
  "library"?: LibraryConfig | null;
  /**
   * Whether this is a dev or production build
   * @default "development"
   */
  "mode"?: BuildMode;
  /**
   * Node.js polyfills for browser builds
   * @default false
   */
  "nodePolyfills"?: boolean;
  /**
   * Optimization config (matches pledge.json format)
Supports: { minify: bool, tree_shake: bool, split_chunks: bool }
   */
  "optimize"?: OptimizeConfig | null;
  /**
   * Output directory (default: ".pledge")
   * @default ".pledge"
   */
  "outDir"?: string;
  /**
   * Output format ("esm" or "cjs")
   * @default "esm"
   */
  "outputFormat"?: OutputFormat;
  /**
   * Plugin trust policy — signature + capability enforcement for
`plugins` (default: signed plugins required).
   */
  "pluginSecurity"?: PluginSecurityConfig;
  /** Plugin paths (JS/TS plugins to load) */
  "plugins"?: string[];
  /**
   * Plugin presets to apply (#94)
presets: ['react', 'tailwind'] applies a bundle of plugins with sensible defaults
   */
  "presets"?: string[];
  /**
   * Build profiling (timing per phase)
   * @default false
   */
  "profile"?: boolean;
  /** Proxy rules for dev server (path prefix → target URL) */
  "proxy"?: ProxyConfig[];
  /**
   * Nested resolve config (alternative to flat fields, matches pledge.json format)
Supports: { alias: [...], extensions: [...], conditions: [...] }
   */
  "resolve"?: ResolveConfig | null;
  /** Resolve aliases (e.g., { "@": "./src" }) */
  "resolveAlias"?: PathAlias[];
  /**
   * Root directory of the project (default: cwd)
   * @default ""
   */
  "root"?: string;
  /** Security configuration (#81, #82)
security: { sri: true, csp: 'auto' } */
  "security"?: SecurityConfig | null;
  /**
   * Server entry point for SSR/API routes (enables server-only code hot reload)
   */
  "serverEntry"?: string | null;
  /**
   * Whether to enable source maps
   * @default true
   */
  "sourceMaps"?: boolean;
  /**
   * Treat problems in the config file itself (unknown / misspelled keys,
no entry point) as errors instead of warnings. Also enabled by the
global `--strict` CLI flag. Default: false.
   * @default false
   */
  "strict"?: boolean;
  /**
   * Service worker caching strategies (#113)
sw: { caching: [{ pattern: '/api/*', strategy: 'network-first' }] }
   */
  "sw"?: SwCachingConfig | null;
  /**
   * Build target(s) for multi-platform output
Supports: "browser" (default), "node", "worker", "edge", or array for multiple targets
Example: target: ["browser", "node"] builds both browser and Node.js bundles
   * @default "browser"
   */
  "target"?: TargetConfig;
  /** Template language configuration (Pug, Handlebars, EJS) */
  "templates"?: TemplateConfig;
  /** Test configuration (Vitest-compatible) */
  "test"?: TestConfig;
  /**
   * Custom transformer pipeline (#97)
transform: { pipeline: ['oxc', 'custom-transform', 'minify'] }
Insert custom transform steps at any point in the pipeline
   */
  "transformPipeline"?: TransformPipelineConfig | null;
  /** Watch mode configuration for production builds */
  "watch"?: WatchConfig;
  /**
   * Build event webhooks (#105)
POST build results to external services on completion
   */
  "webhooks"?: WebhookConfig;
  /**
   * Workspace configuration (#98, #99, #100)
workspaces: true enables auto-detection of npm/pnpm/yarn workspaces
   */
  "workspaces"?: WorkspaceConfig | null;
}

/**
 * Identity helper so `pledge.config.ts` gets typed autocompletion.
 * The native binary reads the config file directly; this only shapes the
 * TypeScript/IDE experience.
 */
export declare function defineConfig(config: PledgeConfig): PledgeConfig;
