[package]
name = "pledgepack-adapter-next"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Next.js adapter for PledgePack"
repository = "https://github.com/pledgeandgrow/pledgepack"
keywords = ["bundler", "build", "rust"]
categories = ["web-programming", "compilers"]

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pledgepack-core = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
